"""Add vehicle info to users

Revision ID: 89b41ee7e893
Revises: 
Create Date: 2025-10-19 05:33:12.453453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b41ee7e893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('chassis', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('make')
        batch_op.drop_column('year')
        batch_op.drop_column('chassis')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
